kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: standard